### PR TITLE
Us461955 deprecation

### PR DESCRIPTION
**Pull request by jhoongo**

### CODE REVIEW

**Comment by ghost** [comment]
Result of [Integration 1](https://stlt.herokuapp.com/v1/xcs_deeplink/qa-mas-mac-mini-1.ca.com/b6c0710ef5081d821be76a414b004419/bf7ff865d5276709cdd493b247004570)
---
*Duration*: 2 minutes and 34 seconds
*Result*: All 0 tests passed, but please **fix 40 warnings** and **17 analyzer warnings**.

**Comment by ghost** [comment]
Result of [Integration 2](https://stlt.herokuapp.com/v1/xcs_deeplink/qa-mas-mac-mini-1.ca.com/b6c0710ef5081d821be76a414b004419/bf7ff865d5276709cdd493b247049ebb)
---
*Duration*: 2 minutes and 2 seconds
*Result*: All 0 tests passed, but please **fix 40 warnings** and **17 analyzer warnings**.

**Comment by ghost** [comment]
Result of [Integration 3](https://stlt.herokuapp.com/v1/xcs_deeplink/qa-mas-mac-mini-1.ca.com/b6c0710ef5081d821be76a414b004419/bf7ff865d5276709cdd493b24705fe51)
---
*Duration*: 1 minute and 51 seconds
*Result*: All 0 tests passed, but please **fix 35 warnings** and **17 analyzer warnings**.

**Comment by ghost** [comment]
Result of [Integration 4](https://stlt.herokuapp.com/v1/xcs_deeplink/qa-mas-mac-mini-1.ca.com/b6c0710ef5081d821be76a414b004419/bf7ff865d5276709cdd493b247062f7e)
---
*Duration*: 1 minute and 51 seconds
*Result*: All 0 tests passed, but please **fix 35 warnings** and **17 analyzer warnings**.

**Review by lsanches — APPROVED** [review]
Approved!

**Pull request merged**
