### PR TITLE
Us507854 capture device metadata

### PR DESCRIPTION
**Pull request by rodrigoareis**

### CODE REVIEW

**Review by jhoongo — DISMISSED** [review]
looks good to me

**Comment by ghost** [comment]
Result of [Integration 1](https://stlt.herokuapp.com/v1/xcs_deeplink/qa-mas-mac-mini-1.ca.com/ca9d5e3b552848330a4baf93320000b4/ca9d5e3b552848330a4baf9332001ccb)
---
*Duration*: 1 minute and 59 seconds
*Result*: **2 errors, failing state: build-errors**

**Comment by ghost** [comment]
Result of [Integration 2](https://stlt.herokuapp.com/v1/xcs_deeplink/qa-mas-mac-mini-1.ca.com/ca9d5e3b552848330a4baf93320000b4/ca9d5e3b552848330a4baf93320416ec)
---
*Duration*: 1 minute and 54 seconds
*Result*: **2 errors, failing state: build-errors**

**Comment by ghost** [comment]
Result of [Integration 3](https://stlt.herokuapp.com/v1/xcs_deeplink/qa-mas-mac-mini-1.ca.com/ca9d5e3b552848330a4baf93320000b4/ca9d5e3b552848330a4baf93322e76f8)
---
*Duration*: 3 minutes and 52 seconds
*Result*: All 0 tests passed, but please **fix 46 warnings** and **19 analyzer warnings**.

**Review by jhoongo — APPROVED** [review]
looks good to me

**Comment by ghost** [comment]
Result of [Integration 4](https://stlt.herokuapp.com/v1/xcs_deeplink/qa-mas-mac-mini-1.ca.com/ca9d5e3b552848330a4baf93320000b4/ca9d5e3b552848330a4baf93323ea04f)
---
*Duration*: 3 minutes and 55 seconds
*Result*: All 0 tests passed, but please **fix 47 warnings** and **19 analyzer warnings**.

**Pull request merged**
