### PR TITLE
New logout method implementation

### PR DESCRIPTION
**Pull request by rodrigoareis**

### CODE REVIEW

**Comment by ghost** [comment]
Result of [Integration 1](https://stlt.herokuapp.com/v1/xcs_deeplink/qa-mas-mac-mini-1.ca.com/bfdf95b94c183c5c09f060b4c33c88b7/bfdf95b94c183c5c09f060b4c33ca4b5)
---
*Duration*: 4 minutes and 26 seconds
*Result*: All 0 tests passed, but please **fix 35 warnings** and **20 analyzer warnings**.

**Comment by ghost** [comment]
Result of [Integration 2](https://stlt.herokuapp.com/v1/xcs_deeplink/qa-mas-mac-mini-1.ca.com/bfdf95b94c183c5c09f060b4c33c88b7/08d223e68722fcc8223c8790abd1fd90)
---
*Duration*: 3 minutes and 43 seconds
*Result*: All 0 tests passed, but please **fix 35 warnings** and **20 analyzer warnings**.

**Comment by ghost** [comment]
Result of [Integration 3](https://stlt.herokuapp.com/v1/xcs_deeplink/qa-mas-mac-mini-1.ca.com/bfdf95b94c183c5c09f060b4c33c88b7/08d223e68722fcc8223c8790abd72045)
---
*Duration*: 3 minutes and 43 seconds
*Result*: All 0 tests passed, but please **fix 35 warnings** and **20 analyzer warnings**.

**Review by jhoongo — APPROVED** [review]
looks good to me

**Pull request merged**
