### PR TITLE
[US509356] : [iOS] Improve geo-location performance

### PR DESCRIPTION
**Pull request by jhoongo**

### CODE REVIEW

**Comment by ghost** [comment]
Result of [Integration 2](https://stlt.herokuapp.com/v1/xcs_deeplink/qa-mas-mac-mini-1.ca.com/15f307e4018b4318848b9ae218252bdd/15f307e4018b4318848b9ae218268e5a)
---
*Duration*: 1 minute and 51 seconds
*Result*: All 0 tests passed, but please **fix 34 warnings** and **18 analyzer warnings**.

**Review by rodrigoareis — DISMISSED** [review]
looks good to me

**Comment by ghost** [comment]
Result of [Integration 3](https://stlt.herokuapp.com/v1/xcs_deeplink/qa-mas-mac-mini-1.ca.com/15f307e4018b4318848b9ae218252bdd/3ba50b5de2950bcd420f5441795a9750)
---
*Duration*: 3 minutes and 51 seconds
*Result*: All 0 tests passed, but please **fix 34 warnings** and **18 analyzer warnings**.

**Comment by ghost** [comment]
Result of [Integration 4](https://stlt.herokuapp.com/v1/xcs_deeplink/qa-mas-mac-mini-1.ca.com/15f307e4018b4318848b9ae218252bdd/3ba50b5de2950bcd420f5441795c75b3)
---
*Duration*: 3 minutes and 47 seconds
*Result*: All 0 tests passed, but please **fix 34 warnings** and **19 analyzer warnings**.

**Review by lsanches — APPROVED** [review]
Approved!

**Pull request merged**
