### PR TITLE
US469003 MASConstants refactory

### PR DESCRIPTION
**Pull request by rodrigoareis**

### CODE REVIEW

**Comment by ghost** [comment]
Result of [Integration 1](https://stlt.herokuapp.com/v1/xcs_deeplink/qa-mas-mac-mini-1.ca.com/e2435b74f89b666f3419cc45d00ffeb9/e2435b74f89b666f3419cc45d01048ac)
---
*Duration*: 5 minutes and 0 second
*Result*: All 0 tests passed, but please **fix 43 warnings** and **17 analyzer warnings**.

**Review by bmckercher — CHANGES_REQUESTED** [review]
Small edits. Take or ignore.

**Review by bmckercher — APPROVED** [review]

**Review by bmckercher — CHANGES_REQUESTED** [review]
Improved organization of static string constants by separating files. The new classes are `MASNotifications` and `MASError`. Also, changed how the SDK exposes the string constants to follow best practices.

**Review by jhoongo — DISMISSED** [review]
looks good to me

**Review by jhoongo — DISMISSED** [review]
looks good to me

**Review by bmckercher — APPROVED** [review]

**Pull request merged**
