### PR TITLE
Added Swift enhancement to this minor release.

### PR DESCRIPTION
**Pull request by bmckercher**
POs decided to release as hotfix so will not be in Release Notes.

### CODE REVIEW

**Comment by ghost** [comment]
Result of [Integration 1](https://stlt.herokuapp.com/v1/xcs_deeplink/qa-mas-mac-mini-1.ca.com/3d6bef58c7f5165d258fea01f5aa9300/3d6bef58c7f5165d258fea01f5aa95c5)
---
*Duration*: 4 minutes and 10 seconds
*Result*: All 0 tests passed, but please **fix 35 warnings** and **17 analyzer warnings**.

**Review by jhoongo — APPROVED** [review]
looks good to me

**Review by bmckercher — COMMENTED** [review]
Good addition. Thanks. Approved.

**Comment by ghost** [comment]
Result of [Integration 2](https://stlt.herokuapp.com/v1/xcs_deeplink/qa-mas-mac-mini-1.ca.com/3d6bef58c7f5165d258fea01f5aa9300/3d6bef58c7f5165d258fea01f5ae2093)
---
*Duration*: 3 minutes and 32 seconds
*Result*: All 0 tests passed, but please **fix 35 warnings** and **17 analyzer warnings**.

**Pull request merged**
