### PR TITLE
US494033 : [iOS] Generic Multi-factor authentication API

### PR DESCRIPTION
**Pull request by jhoongo**

### CODE REVIEW

**Comment by ghost** [comment]
Result of [Integration 1](https://stlt.herokuapp.com/v1/xcs_deeplink/qa-mas-mac-mini-1.ca.com/95596a131be08688ee8bb5cd1400bdf6/95596a131be08688ee8bb5cd1400cc0d)
---
*Duration*: 2 minutes and 22 seconds
*Result*: All 0 tests passed, but please **fix 35 warnings** and **19 analyzer warnings**.

**Comment by ghost** [comment]
Result of [Integration 2](https://stlt.herokuapp.com/v1/xcs_deeplink/qa-mas-mac-mini-1.ca.com/95596a131be08688ee8bb5cd1400bdf6/f984c90eb21de13f77f3d06e220f9438)
---
*Duration*: 3 minutes and 52 seconds
*Result*: All 0 tests passed, but please **fix 35 warnings** and **19 analyzer warnings**.

**Comment by ghost** [comment]
Result of [Integration 3](https://stlt.herokuapp.com/v1/xcs_deeplink/qa-mas-mac-mini-1.ca.com/95596a131be08688ee8bb5cd1400bdf6/f984c90eb21de13f77f3d06e22114472)
---
*Duration*: 3 minutes and 48 seconds
*Result*: All 0 tests passed, but please **fix 35 warnings** and **19 analyzer warnings**.

**Review by rodrigoareis — APPROVED** [review]
Looks good to me

**Pull request merged**
