### PR TITLE
Fix for issue described in DE346442

### PR DESCRIPTION
**Pull request by rodrigoareis**

### CODE REVIEW

**Comment by BobbyWeber** [comment]
Result of [Integration 1](https://stlt.herokuapp.com/v1/xcs_deeplink/qa-mas-mac-mini-1.ca.com/fa35adeef1e77f3f2b1d58ec864fe4c8/fa35adeef1e77f3f2b1d58ec864ff477)
---
*Duration*: 5 minutes and 1 second
*Result*: All 0 tests passed, but please **fix 125 warnings** and **18 analyzer warnings**.

**Comment by BobbyWeber** [comment]
Result of [Integration 2](https://stlt.herokuapp.com/v1/xcs_deeplink/qa-mas-mac-mini-1.ca.com/fa35adeef1e77f3f2b1d58ec864fe4c8/7ea120cb19336248e0151bc02f9d2ff1)
---
*Duration*: 4 minutes and 38 seconds
*Result*: All 0 tests passed, but please **fix 125 warnings** and **18 analyzer warnings**.

**Review by jhoongo — CHANGES_REQUESTED** [review]
Further change request was sent through Rally ticket.

**Review by jhoongo — APPROVED** [review]
looks good to me

**Comment by BobbyWeber** [comment]
Result of [Integration 3](https://stlt.herokuapp.com/v1/xcs_deeplink/qa-mas-mac-mini-1.ca.com/fa35adeef1e77f3f2b1d58ec864fe4c8/6d53c3b2ee46221f4488a9daa60005cf)
---
*Duration*: 2 minutes and 25 seconds
*Result*: All 0 tests passed, but please **fix 125 warnings** and **18 analyzer warnings**.

**Pull request merged**
