### PR TITLE
De347212 mas auth credentials

### PR DESCRIPTION
**Pull request by jhoongo**

### CODE REVIEW

**Comment by ghost** [comment]
Result of [Integration 1](https://stlt.herokuapp.com/v1/xcs_deeplink/qa-mas-mac-mini-1.ca.com/6de403f3bb86c0de3c5f0e42c0ab4fec/6de403f3bb86c0de3c5f0e42c0ab55e6)
---
*Duration*: 4 minutes and 59 seconds
*Result*: All 0 tests passed, but please **fix 40 warnings** and **17 analyzer warnings**.

**Comment by ghost** [comment]
Result of [Integration 2](https://stlt.herokuapp.com/v1/xcs_deeplink/qa-mas-mac-mini-1.ca.com/6de403f3bb86c0de3c5f0e42c0ab4fec/e2435b74f89b666f3419cc45d00e4cc7)
---
*Duration*: 4 minutes and 10 seconds
*Result*: All 0 tests passed, but please **fix 40 warnings** and **17 analyzer warnings**.

**Comment by ghost** [comment]
Result of [Integration 3](https://stlt.herokuapp.com/v1/xcs_deeplink/qa-mas-mac-mini-1.ca.com/6de403f3bb86c0de3c5f0e42c0ab4fec/e2435b74f89b666f3419cc45d01270c8)
---
*Duration*: 4 minutes and 9 seconds
*Result*: All 0 tests passed, but please **fix 40 warnings** and **17 analyzer warnings**.

**Review by spetrov — APPROVED** [review]
Looks good. QA passed too...

**Pull request merged**
