### PR TITLE
Us436059 mqtt

### PR DESCRIPTION
**Pull request by jhoongo**

### CODE REVIEW

**Comment by BobbyWeber** [comment]
Result of [Integration 1](https://stlt.herokuapp.com/v1/xcs_deeplink/qa-mas-mac-mini-1.ca.com/a20b0083fe1c3233bd616bfc2dfaf6c7/a20b0083fe1c3233bd616bfc2dfb269c)
---
*Duration*: 2 minutes and 40 seconds
*Result*: All 0 tests passed, but please **fix 125 warnings** and **18 analyzer warnings**.

**Comment by BobbyWeber** [comment]
Result of [Integration 2](https://stlt.herokuapp.com/v1/xcs_deeplink/qa-mas-mac-mini-1.ca.com/a20b0083fe1c3233bd616bfc2dfaf6c7/0dd350f52463d068499c82a8e38488c8)
---
*Duration*: 2 minutes and 21 seconds
*Result*: All 0 tests passed, but please **fix 125 warnings** and **18 analyzer warnings**.

**Comment by BobbyWeber** [comment]
Result of [Integration 3](https://stlt.herokuapp.com/v1/xcs_deeplink/qa-mas-mac-mini-1.ca.com/a20b0083fe1c3233bd616bfc2dfaf6c7/0dd350f52463d068499c82a8e38a82d3)
---
*Duration*: 2 minutes and 18 seconds
*Result*: All 0 tests passed, but please **fix 125 warnings** and **18 analyzer warnings**.

**Comment by BobbyWeber** [comment]
Result of [Integration 4](https://stlt.herokuapp.com/v1/xcs_deeplink/qa-mas-mac-mini-1.ca.com/a20b0083fe1c3233bd616bfc2dfaf6c7/ea316862d014642e882a2405e5a253d9)
---
*Duration*: 2 minutes and 16 seconds
*Result*: All 0 tests passed, but please **fix 125 warnings** and **18 analyzer warnings**.

**Review by lsanches — APPROVED** [review]
Approved!

**Comment by BobbyWeber** [comment]
Result of [Integration 5](https://stlt.herokuapp.com/v1/xcs_deeplink/qa-mas-mac-mini-1.ca.com/a20b0083fe1c3233bd616bfc2dfaf6c7/1a5d01fdb494b44ad76b12decd947de7)
---
*Duration*: 2 minutes and 34 seconds
*Result*: All 0 tests passed, but please **fix 125 warnings** and **18 analyzer warnings**.

**Pull request merged**
