### PR TITLE
DE331046 : [iOS][MASFoundation] Invalid characters in DC attribute of DN

### PR DESCRIPTION
**Pull request by jhoongo**

### CODE REVIEW

**Review by lsanches — DISMISSED** [review]
Approved!

**Comment by BobbyWeber** [comment]
Result of [Integration 1](https://stlt.herokuapp.com/v1/xcs_deeplink/qa-mas-mac-mini-1.ca.com/a20b0083fe1c3233bd616bfc2dfafe8f/a20b0083fe1c3233bd616bfc2dfb2b70)
---
*Duration*: 2 minutes and 29 seconds
*Result*: All 0 tests passed, but please **fix 125 warnings** and **18 analyzer warnings**.

**Comment by BobbyWeber** [comment]
Result of [Integration 1](https://stlt.herokuapp.com/v1/xcs_deeplink/qa-mas-mac-mini-1.ca.com/a20b0083fe1c3233bd616bfc2dfafe8f/a20b0083fe1c3233bd616bfc2dfb2b70)
---
*Duration*: 2 minutes and 29 seconds
*Result*: All 0 tests passed, but please **fix 125 warnings** and **18 analyzer warnings**.

**Review by BobbyWeber — APPROVED** [review]
Approved with the fixes made

**Pull request merged**
