### PR TITLE
US373049 : [iOS] Register for Push Notification SDK API

### PR DESCRIPTION
**Pull request by rodrigoareis**

### CODE REVIEW

**Review by kayliemoa — APPROVED** [review]

**Review by jhoongo — DISMISSED** [review]
looks good to me

**Comment by BobbyWeber** [comment]
Result of [Integration 1](https://stlt.herokuapp.com/v1/xcs_deeplink/qa-mas-mac-mini-1.ca.com/a20b0083fe1c3233bd616bfc2dfaec64/a20b0083fe1c3233bd616bfc2dfb16a8)
---
*Duration*: 2 minutes and 25 seconds
*Result*: All 0 tests passed, but please **fix 58 warnings** and **16 analyzer warnings**.

**Comment by BobbyWeber** [comment]
Result of [Integration 2](https://stlt.herokuapp.com/v1/xcs_deeplink/qa-mas-mac-mini-1.ca.com/a20b0083fe1c3233bd616bfc2dfaec64/7cdf12270df2d809feb23a760a11cad7)
---
*Duration*: 2 minutes and 14 seconds
*Result*: All 0 tests passed, but please **fix 125 warnings** and **18 analyzer warnings**.

**Comment by ghost** [comment]
Result of [Integration 1](https://stlt.herokuapp.com/v1/xcs_deeplink/qa-mas-mac-mini-1.ca.com/ca9d5e3b552848330a4baf93320011c4/ca9d5e3b552848330a4baf93320019cd)
---
*Duration*: 2 minutes and 18 seconds
*Result*: **2 errors, failing state: build-errors**

**Comment by ghost** [comment]
Result of [Integration 2](https://stlt.herokuapp.com/v1/xcs_deeplink/qa-mas-mac-mini-1.ca.com/ca9d5e3b552848330a4baf93320011c4/ca9d5e3b552848330a4baf93323b0a9f)
---
*Duration*: 3 minutes and 56 seconds
*Result*: All 0 tests passed, but please **fix 130 warnings** and **18 analyzer warnings**.

**Pull request closed without merging**
