### PR TITLE
DE369778 - [iOS][MASFoundation] Device registration flow improvement

### PR DESCRIPTION
**Pull request by jhoongo**

### CODE REVIEW

**Review by rodrigoareis — DISMISSED** [review]
Changes looks good to me

**Comment by ghost** [comment]
Result of [Integration 1](https://stlt.herokuapp.com/v1/xcs_deeplink/qa-mas-mac-mini-1.ca.com/1ac29ea1f354bd4009e4c3079efd1db8/bfed690bc5d68d9172ac4fc0a4062e65)
---
*Duration*: 4 minutes and 32 seconds
*Result*: All 0 tests passed, but please **fix 35 warnings** and **20 analyzer warnings**.

**Comment by ghost** [comment]
Result of [Integration 2](https://stlt.herokuapp.com/v1/xcs_deeplink/qa-mas-mac-mini-1.ca.com/1ac29ea1f354bd4009e4c3079efd1db8/bfdf95b94c183c5c09f060b4c34add34)
---
*Duration*: 3 minutes and 55 seconds
*Result*: All 0 tests passed, but please **fix 35 warnings** and **20 analyzer warnings**.

**Comment by ghost** [comment]
Result of [Integration 3](https://stlt.herokuapp.com/v1/xcs_deeplink/qa-mas-mac-mini-1.ca.com/1ac29ea1f354bd4009e4c3079efd1db8/bfdf95b94c183c5c09f060b4c34c77e8)
---
*Duration*: 3 minutes and 51 seconds
*Result*: All 0 tests passed, but please **fix 35 warnings** and **20 analyzer warnings**.

**Review by lsanches — APPROVED** [review]
Approved!

**Pull request merged**
